version: '3.8'

services:
  db:
    container_name: postgres2
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tracker
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5555:5432"
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    depends_on:
      - db